- name: install ppa jdk
  apt_repository: repo='ppa:webupd8team/java'
  sudo: True

- name: auto accept oracle license
  shell: echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections

- name: install apt Java
  apt: pkg=oracle-java7-installer
  sudo: True

