# config vars: they must be tweaked in inheriting images

alfresco_admin_password: admin
alfresco_version: 4.2.f
dbname: alfresco                                  
dbuser: {name: 'alfresco', password: 'alfresco'}  
dbbindhost: 127.0.0.1
soffice_host: 127.0.0.1
soffice_port: 8100
